'use client';

import { useState } from 'react';
import { Terminal, Folder, Play, ShieldCheck, RefreshCw, Download } from 'lucide-react';
import { getAuthToken } from '@/lib/auth';

interface TerminalWidgetProps {
  projectId: string;
  productName: string;
  uiCode?: string | null;
  blueprint?: any;
}

export default function TerminalWidget({
  projectId,
  productName,
  uiCode,
  blueprint,
}: TerminalWidgetProps) {
  const [targetDir, setTargetDir] = useState(
    productName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'my-generated-saas'
  );
  const [isWriting, setIsWriting] = useState(false);
  const [writeResult, setWriteResult] = useState<any>(null);
  const [logs, setLogs] = useState<string[]>([
    '$ Initializing Recast Terminal Export Engine...',
    `$ Ready to write generated SaaS project code for "${productName}".`,
  ]);

  const [isVerifying, setIsVerifying] = useState(false);
  const [verifyResult, setVerifyResult] = useState<any>(null);

  const [isDownloading, setIsDownloading] = useState(false);
  const [runMd, setRunMd] = useState('');
  const [isFetchingRun, setIsFetchingRun] = useState(false);

  const handleDownload = async () => {
    setIsDownloading(true);
    setLogs((p) => [...p, '$ Building codebase archive…']);
    try {
      const token = getAuthToken();
      const res = await fetch('/api/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({ projectId }),
      });
      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        throw new Error(d.error || `Export failed (HTTP ${res.status})`);
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${targetDir || 'recast-export'}.zip`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1500);
      setLogs((p) => [...p, `✓ Downloaded ${targetDir || 'recast-export'}.zip (${(blob.size / 1024).toFixed(1)} KB)`]);
    } catch (e: any) {
      setLogs((p) => [...p, `[ERROR]: ${e?.message || 'Download failed'}`]);
    } finally {
      setIsDownloading(false);
    }
  };

  const fetchRunInstructions = async () => {
    setIsFetchingRun(true);
    try {
      const token = getAuthToken();
      const res = await fetch('/api/run-instructions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({ projectId }),
      });
      const d = await res.json();
      if (!res.ok || !d.success) throw new Error(d.error || 'Failed to get instructions.');
      setRunMd(d.instructions);
    } catch (e: any) {
      setRunMd(`Could not fetch run instructions — ${e?.message || 'error'}.`);
    } finally {
      setIsFetchingRun(false);
    }
  };

  const handleWriteFiles = async () => {
    if (!targetDir.trim()) return;
    setIsWriting(true);

    const newLogs = [
      ...logs,
      `$ mkdir -p "${targetDir}"`,
      `$ Generating project file tree for "${productName}"...`,
    ];
    setLogs(newLogs);

    try {
      // Build file tree payload
      const filesPayload = [
        {
          path: 'package.json',
          content: JSON.stringify(
            {
              name: productName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
              version: '0.1.0',
              private: true,
              scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
              dependencies: { next: '^14.2.24', react: '^18.3.1', 'react-dom': '^18.3.1', tailwindcss: '^3.4.17' },
            },
            null,
            2
          ),
        },
        {
          path: 'app/page.tsx',
          content: uiCode || `export default function Page() { return <div><h1>${productName}</h1></div>; }`,
        },
        {
          path: 'blueprint.json',
          content: JSON.stringify(blueprint || {}, null, 2),
        },
        {
          path: 'README.md',
          content: `# ${productName}\n\nGenerated by Recast AI Agent.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
        },
      ];

      const token = getAuthToken();
      const res = await fetch('/api/write-files', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ targetDir, files: filesPayload }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || 'Failed to write project files.');
      }

      setWriteResult(data);
      setLogs((prev) => [
        ...prev,
        `✓ Created directory: ${data.targetDir}`,
        ...data.writtenFiles.map((f: string) => `  + Written file: ${f}`),
        `$ Success: ${data.writtenFilesCount} project files written to disk.`,
        `$ Run command: ${data.launchCommand}`,
      ]);
    } catch (err: any) {
      setLogs((prev) => [...prev, `[ERROR]: ${err?.message || 'File export error'}`]);
    } finally {
      setIsWriting(false);
    }
  };

  const handleVerifyServer = async () => {
    setIsVerifying(true);
    setLogs((prev) => [...prev, '$ Testing server verification on http://localhost:3000...']);

    try {
      const token = getAuthToken();
      const res = await fetch('/api/verify-app', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ projectId, url: 'http://localhost:3000' }),
      });

      const data = await res.json();
      setVerifyResult(data);

      if (!res.ok || data.error) {
        setLogs((prev) => [...prev, `[VERIFICATION ERROR]: ${data.error || `HTTP ${res.status}`}`]);
      } else if (data.healthy) {
        setLogs((prev) => [
          ...prev,
          `✓ HTTP 200 OK: Application is running cleanly on ${data.url}`,
        ]);
      } else if (data.healed) {
        setLogs((prev) => [
          ...prev,
          `[VERIFICATION WARNING]: ${data.errorDetected}`,
          `🩺 Self-Healing Coding Agent Triggered! Diagnosing error...`,
          `✓ Code rewritten & patched: ${data.healSummary}`,
          `$ Live Preview updated. Re-testing server verification...`,
        ]);
      }
    } catch (err: any) {
      setLogs((prev) => [...prev, `[VERIFICATION ERROR]: ${err?.message}`]);
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <div className="panel recast-in">
      <div className="rule-b border-line p-4 sm:p-5">
        <span className="section-num">05 — EXPORT</span>
        <h3 className="font-display text-lg font-semibold text-bone mt-1.5">Take the codebase</h3>
        <p className="text-[12px] text-steel mt-0.5">Download every generated file as a .zip — works here and on the deployed app.</p>
      </div>
      <div className="p-4 sm:p-5 space-y-5">

      {/* Download the whole codebase */}
      <div className="border border-line p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <div className="mono-label !text-bone">DOWNLOAD .ZIP</div>
          <p className="text-[12px] text-steel mt-1">
            All generated files + <code className="text-molten">RUN.md</code> + README. Nothing is written to a server.
          </p>
        </div>
        <button
          onClick={handleDownload}
          disabled={isDownloading}
          className="bg-molten hover:opacity-90 text-ink px-5 py-2.5 font-mono font-bold text-[10px] uppercase tracking-[0.14em] flex items-center justify-center gap-2 shrink-0 disabled:opacity-40 transition-opacity"
        >
          {isDownloading ? 'Zipping…' : 'Download .zip'}
          <Download className="w-3.5 h-3.5" />
        </button>
      </div>

      {/* How to run it — Groq */}
      <div className="border border-line p-4 space-y-3">
        <div className="flex items-center justify-between gap-3">
          <div className="mono-label !text-bone">HOW TO RUN IT</div>
          <button
            onClick={fetchRunInstructions}
            disabled={isFetchingRun}
            className="mono-label hover:text-molten disabled:opacity-40 transition-colors"
          >
            {isFetchingRun ? 'asking groq…' : runMd ? 'refresh' : 'get instructions →'}
          </button>
        </div>
        {runMd && (
          <pre className="bg-ink border border-line p-3 text-[11px] font-mono text-bone/90 whitespace-pre-wrap overflow-auto leading-relaxed max-h-[320px]">
{runMd}
          </pre>
        )}
      </div>

      {/* Local-only disk export */}
      <div className="space-y-2 bg-ink border border-line p-4 rounded-none">
        <label className="mono-label !text-bone flex items-center gap-2">
          <Folder className="w-3.5 h-3.5 text-molten" />
          Write to disk — local dev only
        </label>
        <p className="text-[11px] text-steel">
          Writes into a sandboxed <code className="text-molten font-mono">.exports/</code> folder on the machine running the app. Returns 501 on a deployed server — use the .zip instead.
        </p>
        <div className="flex flex-col sm:flex-row gap-2">
          <input
            type="text"
            value={targetDir}
            onChange={(e) => setTargetDir(e.target.value)}
            placeholder="my-generated-saas"
            className="flex-1 bg-ink-soft border border-line rounded-none px-3.5 py-2.5 text-xs text-bone placeholder-steel focus:outline-none font-mono focus:border-molten/60"
          />
          <button
            onClick={handleWriteFiles}
            disabled={isWriting || !targetDir.trim()}
            className="bg-ink-soft hover:bg-ink-2 text-bone border border-line font-mono font-bold text-[10px] uppercase tracking-[0.12em] px-4 py-2.5 rounded-none flex items-center justify-center gap-2 shrink-0 disabled:opacity-50 transition-colors"
          >
            {isWriting ? 'Writing…' : (<><Play className="w-3 h-3 fill-current" /> Write to disk</>)}
          </button>
        </div>
      </div>

      {/* Interactive CLI Console */}
      <div className="bg-ink border border-line rounded-none overflow-hidden font-mono text-xs ">
        <div className="bg-ink-soft border-b border-line px-3.5 py-2 flex items-center justify-between text-[10px] text-steel">
          <span className="flex items-center gap-2 font-mono font-semibold">
            <span className="w-2 h-2 rounded-full bg-emerald-400"></span> TERMINAL CLI CONSOLE
          </span>
          <span>powershell / bash</span>
        </div>
        <div className="p-4 space-y-1.5 min-h-[160px] max-h-[260px] overflow-y-auto text-bone/80">
          {logs.map((log, idx) => (
            <div
              key={idx}
              className={`${
                log.startsWith('✓') || log.includes('Success')
                  ? 'text-emerald-400 font-semibold'
                  : log.startsWith('[ERROR]') || log.startsWith('[VERIFICATION WARNING]')
                  ? 'text-rose-400 font-semibold'
                  : log.startsWith('$')
                  ? 'text-molten'
                  : 'text-steel'
              }`}
            >
              {log}
            </div>
          ))}
        </div>
      </div>

      {/* Self-Healing Health Verification Trigger */}
      <div className="bg-ink border border-line p-4 rounded-none flex flex-col sm:flex-row items-center justify-between gap-3">
        <div>
          <h4 className="text-xs font-bold text-bone flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            Automated Health Check & Self-Healing Verifier
          </h4>
          <p className="text-[11px] text-steel mt-0.5">
            Checks target server health on <code className="text-molten font-mono">http://localhost:3000</code>. Automatically rewrites code if errors occur.
          </p>
        </div>

        <button
          onClick={handleVerifyServer}
          disabled={isVerifying}
          className="bg-ink-soft hover:bg-ink-2 text-bone font-bold text-xs px-4 py-2.5 rounded-none border border-line flex items-center space-x-2 shrink-0 transition-all disabled:opacity-50"
        >
          {isVerifying ? (
            <>
              <RefreshCw className="w-3.5 h-3.5 animate-spin text-molten" />
              <span>Verifying Health...</span>
            </>
          ) : (
            <>
              <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
              <span>Run Verification Check</span>
            </>
          )}
        </button>
      </div>
      </div>
    </div>
  );
}
