'use client';

import { useState } from 'react';
import { Terminal, Folder, Play, Check, ShieldCheck, RefreshCw, AlertTriangle, ArrowRight } from 'lucide-react';
import { getAuthToken } from '@/lib/auth';

interface TerminalWidgetProps {
  projectId: string;
  productName: string;
  uiCode?: string | null;
  blueprint?: any;
}

export default function TerminalWidget({
  projectId,
  productName,
  uiCode,
  blueprint,
}: TerminalWidgetProps) {
  const [targetDir, setTargetDir] = useState(
    productName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'my-generated-saas'
  );
  const [isWriting, setIsWriting] = useState(false);
  const [writeResult, setWriteResult] = useState<any>(null);
  const [logs, setLogs] = useState<string[]>([
    '$ Initializing Recast Terminal Export Engine...',
    `$ Ready to write generated SaaS project code for "${productName}".`,
  ]);

  const [isVerifying, setIsVerifying] = useState(false);
  const [verifyResult, setVerifyResult] = useState<any>(null);

  const handleWriteFiles = async () => {
    if (!targetDir.trim()) return;
    setIsWriting(true);

    const newLogs = [
      ...logs,
      `$ mkdir -p "${targetDir}"`,
      `$ Generating project file tree for "${productName}"...`,
    ];
    setLogs(newLogs);

    try {
      // Build file tree payload
      const filesPayload = [
        {
          path: 'package.json',
          content: JSON.stringify(
            {
              name: productName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
              version: '0.1.0',
              private: true,
              scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
              dependencies: { next: '^14.2.24', react: '^18.3.1', 'react-dom': '^18.3.1', tailwindcss: '^3.4.17' },
            },
            null,
            2
          ),
        },
        {
          path: 'app/page.tsx',
          content: uiCode || `export default function Page() { return <div><h1>${productName}</h1></div>; }`,
        },
        {
          path: 'blueprint.json',
          content: JSON.stringify(blueprint || {}, null, 2),
        },
        {
          path: 'README.md',
          content: `# ${productName}\n\nGenerated by Recast AI Agent.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
        },
      ];

      const token = getAuthToken();
      const res = await fetch('/api/write-files', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ targetDir, files: filesPayload }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || 'Failed to write project files.');
      }

      setWriteResult(data);
      setLogs((prev) => [
        ...prev,
        `✓ Created directory: ${data.targetDir}`,
        ...data.writtenFiles.map((f: string) => `  + Written file: ${f}`),
        `$ Success: ${data.writtenFilesCount} project files written to disk.`,
        `$ Run command: ${data.launchCommand}`,
      ]);
    } catch (err: any) {
      setLogs((prev) => [...prev, `[ERROR]: ${err?.message || 'File export error'}`]);
    } finally {
      setIsWriting(false);
    }
  };

  const handleVerifyServer = async () => {
    setIsVerifying(true);
    setLogs((prev) => [...prev, '$ Testing server verification on http://localhost:3000...']);

    try {
      const token = getAuthToken();
      const res = await fetch('/api/verify-app', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ projectId, url: 'http://localhost:3000' }),
      });

      const data = await res.json();
      setVerifyResult(data);

      if (!res.ok || data.error) {
        setLogs((prev) => [...prev, `[VERIFICATION ERROR]: ${data.error || `HTTP ${res.status}`}`]);
      } else if (data.healthy) {
        setLogs((prev) => [
          ...prev,
          `✓ HTTP 200 OK: Application is running cleanly on ${data.url}`,
        ]);
      } else if (data.healed) {
        setLogs((prev) => [
          ...prev,
          `[VERIFICATION WARNING]: ${data.errorDetected}`,
          `🩺 Self-Healing Coding Agent Triggered! Diagnosing error...`,
          `✓ Code rewritten & patched: ${data.healSummary}`,
          `$ Live Preview updated. Re-testing server verification...`,
        ]);
      }
    } catch (err: any) {
      setLogs((prev) => [...prev, `[VERIFICATION ERROR]: ${err?.message}`]);
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <div className="bg-ink-soft border border-line rounded-none p-6 sm:p-8  space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-line pb-4">
        <div className="flex items-center space-x-3">
          <div className="w-8 h-8 rounded-none bg-ink border border-line flex items-center justify-center text-molten">
            <Terminal className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-bone flex items-center gap-2">
              Terminal File System Writer & Self-Healing Verifier
            </h3>
            <p className="text-xs text-steel">Target path prompt, file writer, and automated health checks.</p>
          </div>
        </div>
      </div>

      {/* Location Input Form */}
      <div className="space-y-2 bg-ink border border-line p-4 rounded-none">
        <label className="text-xs font-bold text-bone flex items-center space-x-2">
          <Folder className="w-4 h-4 text-molten" />
          <span>Export Folder Name:</span>
        </label>
        <p className="text-[11px] text-steel -mt-1">
          Files are written to a sandboxed <code className="text-molten font-mono">.exports/</code> directory on the server under this folder name.
        </p>
        <div className="flex flex-col sm:flex-row gap-2">
          <input
            type="text"
            value={targetDir}
            onChange={(e) => setTargetDir(e.target.value)}
            placeholder="my-generated-saas"
            className="flex-1 bg-ink-soft border border-line rounded-none px-3.5 py-2.5 text-xs text-bone placeholder-steel focus:outline-none font-mono focus:border-molten/60"
          />
          <button
            onClick={handleWriteFiles}
            disabled={isWriting || !targetDir.trim()}
            className="bg-molten hover:opacity-90 text-ink font-bold text-xs px-5 py-2.5 rounded-none  flex items-center justify-center space-x-2 shrink-0 disabled:opacity-50 transition-all active:scale-95"
          >
            {isWriting ? (
              <>
                <div className="w-3.5 h-3.5 rounded-full border-2 border-ink/40 border-t-ink animate-spin"></div>
                <span>Writing Files...</span>
              </>
            ) : (
              <>
                <Play className="w-3.5 h-3.5 fill-current" />
                <span>Write Files to Disk</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Interactive CLI Console */}
      <div className="bg-ink border border-line rounded-none overflow-hidden font-mono text-xs ">
        <div className="bg-ink-soft border-b border-line px-3.5 py-2 flex items-center justify-between text-[10px] text-steel">
          <span className="flex items-center gap-2 font-mono font-semibold">
            <span className="w-2 h-2 rounded-full bg-emerald-400"></span> TERMINAL CLI CONSOLE
          </span>
          <span>powershell / bash</span>
        </div>
        <div className="p-4 space-y-1.5 min-h-[160px] max-h-[260px] overflow-y-auto text-bone/80">
          {logs.map((log, idx) => (
            <div
              key={idx}
              className={`${
                log.startsWith('✓') || log.includes('Success')
                  ? 'text-emerald-400 font-semibold'
                  : log.startsWith('[ERROR]') || log.startsWith('[VERIFICATION WARNING]')
                  ? 'text-rose-400 font-semibold'
                  : log.startsWith('$')
                  ? 'text-molten'
                  : 'text-steel'
              }`}
            >
              {log}
            </div>
          ))}
        </div>
      </div>

      {/* Self-Healing Health Verification Trigger */}
      <div className="bg-ink border border-line p-4 rounded-none flex flex-col sm:flex-row items-center justify-between gap-3">
        <div>
          <h4 className="text-xs font-bold text-bone flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            Automated Health Check & Self-Healing Verifier
          </h4>
          <p className="text-[11px] text-steel mt-0.5">
            Checks target server health on <code className="text-molten font-mono">http://localhost:3000</code>. Automatically rewrites code if errors occur.
          </p>
        </div>

        <button
          onClick={handleVerifyServer}
          disabled={isVerifying}
          className="bg-ink-soft hover:bg-ink-2 text-bone font-bold text-xs px-4 py-2.5 rounded-none border border-line flex items-center space-x-2 shrink-0 transition-all disabled:opacity-50"
        >
          {isVerifying ? (
            <>
              <RefreshCw className="w-3.5 h-3.5 animate-spin text-molten" />
              <span>Verifying Health...</span>
            </>
          ) : (
            <>
              <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
              <span>Run Verification Check</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
}
