// A minimal, runnable Next.js 14 (App Router) + TypeScript + Tailwind scaffold.
// The export route fills in any of these files the generated project is missing,
// so `npm install && npm run dev` always works out of the box.

export function scaffoldFiles(projectSlug: string): Record<string, string> {
  return {
    'package.json': JSON.stringify(
      {
        name: projectSlug || 'recast-app',
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          next: '14.2.24',
          react: '18.3.1',
          'react-dom': '18.3.1',
          'lucide-react': '0.475.0',
        },
        devDependencies: {
          typescript: '5.7.3',
          '@types/node': '20.17.19',
          '@types/react': '18.3.18',
          '@types/react-dom': '18.3.5',
          tailwindcss: '3.4.17',
          postcss: '8.5.2',
          autoprefixer: '10.4.20',
          eslint: '8.57.1',
          'eslint-config-next': '14.2.24',
        },
      },
      null,
      2
    ) + '\n',

    'next.config.mjs': `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
export default nextConfig;
`,

    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: false,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2
    ) + '\n',

    'next-env.d.ts': `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,

    'tailwind.config.ts': `import type { Config } from 'tailwindcss';
const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}', './lib/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`,

    'postcss.config.js': `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };
`,

    'app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;
`,

    'app/layout.tsx': `import './globals.css';
import type { ReactNode } from 'react';

export const metadata = { title: '${projectSlug || 'App'}' };

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,

    '.gitignore': `node_modules
.next
out
.env*.local
.DS_Store
*.tsbuildinfo
next-env.d.ts
`,

    '.env.example': `# Fill in any keys the generated code references, then copy to .env.local
`,

    'app/page.tsx': `export default function Page() {
  return (
    <main style={{ padding: 32, fontFamily: 'system-ui, sans-serif' }}>
      <h1>${projectSlug || 'App'}</h1>
      <p>Generated by Recast. Replace this file with your real home page.</p>
    </main>
  );
}
`,
  };
}
