import { generateRunInstructions } from '@/lib/ai';
import { getProjectById } from '@/lib/store';
import { getAuthenticatedUser } from '@/lib/auth-server';
import { enforceRateLimit } from '@/lib/rate-limit';
import { createZip, ZipEntry } from '@/lib/zip';
import { scaffoldFiles } from '@/lib/scaffold';
import { tidyFileContent } from '@/lib/format';
import { ProjectFile } from '@/types';
import { NextResponse } from 'next/server';

// Builds the whole generated codebase into a runnable .zip in memory and
// returns it as a download. Any standard Next.js project files the generated
// code is missing (package.json, config, app/layout.tsx, …) are filled in so
// `npm install && npm run dev` works out of the box. Serverless-safe.
export async function POST(request: Request) {
  try {
    const user = await getAuthenticatedUser(request);
    if (!user) return NextResponse.json({ error: 'Unauthorized. Please log in.' }, { status: 401 });

    const limited = enforceRateLimit(user.id, 'export', 10, 60_000);
    if (limited) return limited;

    const { projectId } = await request.json();
    if (!projectId) return NextResponse.json({ error: 'Project ID is required.' }, { status: 400 });

    const project = await getProjectById(projectId, user.id);
    if (!project || project.userId !== user.id) {
      return NextResponse.json({ error: 'Project not found.' }, { status: 404 });
    }

    const files: ProjectFile[] = project.generatedFiles || project.blueprint?.generatedFiles || [];
    if (files.length === 0) {
      return NextResponse.json({ error: 'Nothing generated yet. Build the product first.' }, { status: 404 });
    }

    const slug =
      (project.blueprint?.productName || project.name || 'recast-app')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '') || 'recast-app';

    // Generated files win; scaffold fills every gap needed to actually run.
    const tree = new Map<string, string>();
    for (const f of files) {
      if (f?.path && typeof f.content === 'string') {
        const p = f.path.replace(/^\/+/, '');
        tree.set(p, tidyFileContent(p, f.content));
      }
    }
    const scaffold = scaffoldFiles(slug);
    for (const [path, content] of Object.entries(scaffold)) {
      if (!tree.has(path)) tree.set(path, content);
    }

    // Docs — give Groq the scaffold-merged tree so it sees package.json.
    let runMd = '';
    try {
      if (project.blueprint) {
        const merged: ProjectFile[] = Array.from(tree.entries()).map(([path, content]) => ({
          path,
          name: path.split('/').pop() || path,
          type: 'frontend',
          language: path.endsWith('.json') ? 'json' : 'typescript',
          content,
        }));
        runMd = await generateRunInstructions(project.blueprint, merged);
      }
    } catch {
      /* non-fatal */
    }
    tree.set(
      'SETUP.md',
      `# ${project.blueprint?.productName || project.name}

Generated by Recast${project.websiteUrl ? ` from ${project.websiteUrl}` : ''}.

## Run it (Next.js 14 + TypeScript + Tailwind)

Requires **Node.js 18+**.

\`\`\`bash
npm install
cp .env.example .env.local   # then fill in any keys the code references
npm run dev
\`\`\`

Open http://localhost:3000

## Build for production

\`\`\`bash
npm run build && npm start
\`\`\`
`
    );
    if (runMd) tree.set('RUN.md', runMd);
    if (project.blueprint) tree.set('recast.blueprint.json', JSON.stringify(project.blueprint, null, 2));

    // Files live at the zip root — extract the archive and `cd` straight in.
    const entries: ZipEntry[] = Array.from(tree.entries()).map(([path, content]) => ({ path, content }));
    const zip = createZip(entries);

    return new Response(new Uint8Array(zip), {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${slug}.zip"`,
        'Content-Length': String(zip.length),
        'Cache-Control': 'no-store',
      },
    });
  } catch (err: any) {
    console.error('API /api/export error:', err);
    return NextResponse.json({ error: err?.message || 'Failed to export the project.' }, { status: 500 });
  }
}
