import { generateRunInstructions } from '@/lib/ai';
import { getProjectById } from '@/lib/store';
import { getAuthenticatedUser } from '@/lib/auth-server';
import { enforceRateLimit } from '@/lib/rate-limit';
import { createZip, ZipEntry } from '@/lib/zip';
import { ProjectFile } from '@/types';
import { NextResponse } from 'next/server';

// Builds the whole generated codebase into a .zip in memory and returns it as
// a download. Works identically locally and on serverless (no filesystem).
export async function POST(request: Request) {
  try {
    const user = await getAuthenticatedUser(request);
    if (!user) return NextResponse.json({ error: 'Unauthorized. Please log in.' }, { status: 401 });

    const limited = enforceRateLimit(user.id, 'export', 10, 60_000);
    if (limited) return limited;

    const { projectId } = await request.json();
    if (!projectId) return NextResponse.json({ error: 'Project ID is required.' }, { status: 400 });

    const project = await getProjectById(projectId, user.id);
    if (!project || project.userId !== user.id) {
      return NextResponse.json({ error: 'Project not found.' }, { status: 404 });
    }

    const files: ProjectFile[] = project.generatedFiles || project.blueprint?.generatedFiles || [];
    if (files.length === 0) {
      return NextResponse.json({ error: 'Nothing generated yet. Build the product first.' }, { status: 404 });
    }

    const slug =
      (project.blueprint?.productName || project.name || 'recast-export')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '') || 'recast-export';

    let runMd = '';
    try {
      if (project.blueprint) runMd = await generateRunInstructions(project.blueprint, files);
    } catch {
      /* non-fatal — export still works without RUN.md */
    }

    const entries: ZipEntry[] = files.map((f) => ({ path: `${slug}/${f.path}`, content: f.content }));

    entries.push({
      path: `${slug}/RUN.md`,
      content:
        runMd ||
        `# Run ${project.blueprint?.productName || project.name}\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    });
    entries.push({
      path: `${slug}/README.md`,
      content: `# ${project.blueprint?.productName || project.name}\n\n${
        project.blueprint?.description || project.description || ''
      }\n\nGenerated by Recast from ${project.websiteUrl || 'an idea'}. See RUN.md to get it running.\n`,
    });
    if (project.blueprint) {
      entries.push({ path: `${slug}/recast.blueprint.json`, content: JSON.stringify(project.blueprint, null, 2) });
    }

    const zip = createZip(entries);

    return new Response(new Uint8Array(zip), {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${slug}.zip"`,
        'Content-Length': String(zip.length),
        'Cache-Control': 'no-store',
      },
    });
  } catch (err: any) {
    console.error('API /api/export error:', err);
    return NextResponse.json({ error: err?.message || 'Failed to export the project.' }, { status: 500 });
  }
}
